.semver
App/Components/Authentification/Controller.php
App/Components/Utilisateur/Dao.php
App/Components/Utilisateur/Model.php
App/Components/Utilisateur/Repository.php
App/Helpers/Formatter.php
Middlewares.php
Middlewares/Identification.php
README.md
Tests/Units/App/Components/Utilisateur/Dao.php
Tests/Units/App/Components/Utilisateur/Model.php
Tests/Units/App/Components/Utilisateur/Repository.php
Tests/Units/App/Helpers/Formatter.php
Tests/Units/Middlewares/Identification.php
configuration.json.example

Fix #16 
Fix #15
Le mécanisme de gestion de token a été très erratique. La dernière version en date, ici, créé un token pour une durée de 5 minutes (repoussée à chaque nouvelle requête) et génère un champ avec des caractères spéciaux mais utilisables dans une requête (pas comme la précédente). Sécurisé mais potentiellement reversible, cette version rendra un meilleur service. À présent, toutes les requêtes (sauf l'authentification) devront montrer patte blanche avec la transmission du token via le header `Token [aaaaaa]`.
Testable facilement avec un docker + l'addon httpRequester

Amélioration du système de token et de sa durée de vie

---

App/Components/Planning/Controller.php
App/Components/Planning/Creneau/Controller.php
App/Components/Planning/Creneau/Entite.php
App/Components/Planning/Creneau/Repository.php
App/Components/Planning/Entite.php
App/Components/Planning/Repository.php
App/Components/Utilisateur/Entite.php
App/Components/Utilisateur/Repository.php
App/Libraries/AEntite.php
App/Libraries/ARepository.php
Middlewares/Identification.php
Tests/Units/App/Components/Authentification/Controller.php
Tests/Units/App/Components/Planning/Controller.php
Tests/Units/App/Components/Planning/Creneau/Controller.php
Tests/Units/App/Components/Planning/Creneau/Entite.php
Tests/Units/App/Components/Planning/Creneau/Model.php
Tests/Units/App/Components/Planning/Creneau/Repository.php
Tests/Units/App/Components/Planning/Entite.php
Tests/Units/App/Components/Planning/Model.php
Tests/Units/App/Components/Planning/Repository.php
Tests/Units/App/Components/Utilisateur/Entite.php
Tests/Units/App/Components/Utilisateur/Model.php
Tests/Units/App/Components/Utilisateur/Repository.php
Tests/Units/App/Libraries/AEntite.php
Tests/Units/App/Libraries/AModel.php
Tests/Units/Middlewares/Identification.php
decisions.md

Fix #6
Le design architectural MVC ne signifie pas qu'il y a 3 classes, il signifie qu'il y a trois couches de responsabilités (`3-tier architecture`). Pour éviter tout doute sur ce que doit être la couche `Model`, je renomme la classe entre un autre nom, tout aussi signifiant sur ce qu'elle fait mais en évitant l'écueil énoncé.
J'en profite, du coup, pour dire que la couche `Model` se compose actuellement de : 
* Repository, chef d'orchestre et point d'entrée métier,
* Entité, ou domain model, représentant d'une sphère d'influence métier, avec des règles métier appliquées à des données,
* DAO, interacteur avec le stockage.

Changement de nom vers Entité

---

Tests/Units/Tools/Libraries/AControllerFactory.php
Tools/Libraries/AControllerFactory.php
Tools/Middlewares.php
Tools/Route/Authentification.php
Tools/Route/Plannings.php
Tools/Route/Utilisateurs.php
Utilisateur/UtilisateurController.php

Les fichiers de route s'appuyaient sur un namespace pour le matching avec le contrôleur créé préalablement. C'est source de confusion. Comme il n'y aura toujours qu'un contrôleur de lancé à un instant T, je supprime ce nom et simplifie.

Easy Peasy routers

---

Journal/JournalController.php
Journal/JournalDao.php
Journal/JournalEntite.php
Journal/JournalRepository.php
Planning/Creneau/CreneauController.php
Planning/PlanningController.php
Public/index.php
README.md
Tests/Units/Journal/JournalController.php
Tests/Units/Journal/JournalDao.php
Tests/Units/Journal/JournalEntite.php
Tests/Units/Journal/JournalRepository.php
Tests/Units/Tools/Helpers/Formatter.php
Tests/Units/Tools/Libraries/ARestController.php
Tools/Helpers/Formatter.php
Tools/Middlewares.php
Tools/Route/Journal.php
Tools/Route/Planning.php
decisions.md

J'ai ajouté le journal dans l'API, je suis parti du principe qu'il ne devait être qu'en lecture et destruction seules (vis à vis des routes), donc je pense qu'on ne fera pas les autres, ces derniers étant gérés automatiquement par l'API en interne.
À ce propos, je pense que nous gagnerions du temps à ne faire que l'ordre `GET` pour le moment, ça permettra à l'API d'être dispo plus tôt pour le client web, les autres ordres restant côté client. Au fur et à mesure, on transférera les responsabilités.
Sinon... je me suis retrouvé dans un embûche pour la pluralisation des routes ; avec `journaux`, ça me paraissait relou d'avoir une map des mots au singulier / pluriel juste pour suivre une convention. J'ai fait au plus simple, j'ai changé la convention et toutes les routes sont à présent au …

Ajout du journal dans l'API

---

Absence/Type/TypeController.php
Absence/Type/TypeDao.php
Absence/Type/TypeRepository.php
Groupe/GroupeController.php
Groupe/GroupeDao.php
Groupe/GroupeEntite.php
Groupe/GroupeRepository.php
Journal/JournalDao.php
Journal/JournalRepository.php
Planning/Creneau/CreneauController.php
Planning/Creneau/CreneauRepository.php
Planning/PlanningDao.php
Planning/PlanningRepository.php
Public/index.php
Tests/Units/Absence/Type/TypeEntite.php
Tests/Units/Groupe/GroupeController.php
Tests/Units/Groupe/GroupeDao.php
Tests/Units/Groupe/GroupeEntite.php
Tests/Units/Groupe/GroupeRepository.php
Tests/Units/Tools/Libraries/ARestController.php
Tools/Libraries/ADao.php
Tools/Libraries/ARepository.php
Tools/Route/Groupe.php
Utilisateur/UtilisateurController.php

Ajout d'une route liée à l'admin, celle des groupes. Cette route ne présente que les informations de l'identité d'un groupe, ça ne montre pas les associations. En effet, je me donne pour limite à chaque fois 1KLOC (ce qui donne 2 à 4 heures de review) et ajouter les associations aurait fait trop.
J'ai par contre déjà posé la base de ce que devront être les routes d'associations à l'avenir : 
- les responsables : groupe/N/premier_validateur (avec changement de nom pour ne pas confondre avec le rôle, ce n'est pas la même chose)
- les employes : groupe/N/employes
- les grand responsables : groupe/N/second_validateur
J'ai profité que j'étais là pour enlever un truc qui ne nous sert pas pour le moment, ni dans l'API, ni dans la partie web : les prédicats de filtres. Si vraiment on en a besoin …

Ajout de la route pour les groupes

---

Absence/Type/TypeController.php
Absence/Type/TypeDao.php
Groupe/GroupeController.php
Groupe/GroupeDao.php
Groupe/GroupeEntite.php
Groupe/Responsable/ResponsableController.php
Groupe/Responsable/ResponsableDao.php
Groupe/Responsable/ResponsableRepository.php
Journal/JournalController.php
Journal/JournalDao.php
Planning/Creneau/CreneauController.php
Planning/Creneau/CreneauEntite.php
Planning/PlanningController.php
Planning/PlanningEntite.php
Tests/Units/Groupe/Responsable/ResponsableController.php
Tests/Units/Groupe/Responsable/ResponsableDao.php
Tests/Units/Groupe/Responsable/ResponsableRepository.php
Tests/Units/Journal/JournalController.php
Tests/Units/Planning/PlanningController.php
Tests/Units/Tools/Libraries/ARestController.php
Tools/Libraries/ADao.php
Tools/Route/Groupe.php
Utilisateur/UtilisateurController.php
Utilisateur/UtilisateurDao.php
Utilisateur/UtilisateurEntite.php
decisions.md

On avance, petit à petit. Cette PR, en plus de faire son job, pose les bases pour l'ajout quasi instantanée de `groupe_haut_responsable` et `groupe_employe`.
Comme la table derrière cette route est une relation `N-N`, il n'y aucun intérêt de rechercher par id d'entité, il n'y a donc pas de route `GET /groupe/88/responsable/1`, seule la liste est dispo. Parlant des entités, par essence de la relation `N-N`, il ne peut y avoir d'entité représentante. Puisque pour l'instant, l'application a été construite appuyée sur les entités, j'ai pris le parti de brancher le composant `groupe/responsable` sur l'entité `utilisateur`. Ce n'est pas idéal, mais il serait stupide de faire de profondes refacto à chaque fois qu'un nouvel événement arrive ; il vaut mieux patienter, faire remonter les cas et le …

Ajout de la route pour les responsables de groupe

---

Utilisateur/UtilisateurDao.php
Utilisateur/UtilisateurRepository.php

fix #12 
Il est nécessaire de commencer par le travail sur l'API pour le sujet « *migration des mots de passe* ». En effet, nous devons viser la compat' maximale et cela commence par une souplesse de l'API. De ce fait, j'ai rajouté un prédicat « OU » dans la recherche de l'utilisateur à authentifier. Le test ne consiste qu'en la vérification que l'authentification se passe bien.
Côté technique, l'algorithme blowfish est compatible avec la taille du stockage alloué au mot de passe dans la db, j'utilise donc en dur ce dernier. Vu l'aspect centralisateur de l'API, le temps qu'il soit cassé, nous n'aurons que cet endroit à modifier.

Migrer les mots de passe vers un algo plus robuste

---

Groupe/Employe/EmployeController.php
Groupe/GrandResponsable/GrandResponsableController.php
Groupe/Responsable/ResponsableController.php
JourFerie/JourFerieController.php
JourFerie/JourFerieDao.php
JourFerie/JourFerieEntite.php
JourFerie/JourFerieRepository.php
Planning/PlanningController.php
Public/index.php
README.md
Tests/Units/JourFerie/JourFerieController.php
Tests/Units/JourFerie/JourFerieDao.php
Tests/Units/JourFerie/JourFerieEntite.php
Tests/Units/JourFerie/JourFerieRepository.php
Tests/Units/Tools/Libraries/ARestController.php
Tools/Route/JourFerie.php
Utilisateur/UtilisateurEntite.php

Nouveau jour, nouvelle table portée sur l'API. Rien de difficile, il nous suffit de copier un package et de changer les informations qui s'y trouvent, le reste suit naturellement. Cependant, comme je m'y attendais, nous découvrons chaque fois des nouvelles choses qui nous font préciser l'ébauche de design que nous avions commencé à mettre en place. En effet, jusque-là un **package métier** était constitué du contrôleur, de l'entité, de la DAO et du repo. Oui mais voilà, une entité se singularise par son identité, là où un jour férié n'a pas en soit d'identité ; ce serait plutôt un value object. 
Puisque ce n'était pas le sujet de la PR, je suis allé au plus simple, j'ai créé une entité JourFerieEntite. Je suppose qu'il va être temps d'utiliser un framework d'injection de dépendance pour …

Accès aux jours fériés via l'API

---

Absence/Type/TypeController.php
Groupe/Employe/EmployeRepository.php
Groupe/GrandResponsable/GrandResponsableRepository.php
Groupe/GroupeController.php
Groupe/Responsable/ResponsableRepository.php
JourFerie/JourFerieRepository.php
Journal/JournalRepository.php
Planning/Creneau/CreneauController.php
Planning/Creneau/CreneauRepository.php
Planning/PlanningController.php
Tests/Units/Absence/Type/TypeController.php
Tests/Units/Absence/Type/TypeRepository.php
Tests/Units/Groupe/Employe/EmployeRepository.php
Tests/Units/Groupe/GrandResponsable/GrandResponsableRepository.php
Tests/Units/Groupe/GroupeController.php
Tests/Units/Groupe/GroupeRepository.php
Tests/Units/Groupe/Responsable/ResponsableRepository.php
Tests/Units/JourFerie/JourFerieRepository.php
Tests/Units/Journal/JournalRepository.php
Tests/Units/Planning/Creneau/CreneauController.php
Tests/Units/Planning/Creneau/CreneauRepository.php
Tests/Units/Planning/PlanningController.php
Tests/Units/Planning/PlanningRepository.php
Tests/Units/Tools/Libraries/ARepository.php
Tests/Units/Utilisateur/UtilisateurRepository.php
Tools/Exceptions/UnknownResourceException.php
Tools/Libraries/ARepository.php
Utilisateur/UtilisateurRepository.php

Les responsabilités étaient bien designées, à ceci près que dans les ordres ReST non safe (POST, PUT, DELETE), le contrôleur faisait un remplissage et / ou vérification sur l'existence de l'entité. Ces opérations étant du ressort du repo, je les déplace donc.

Déplacement des responsabilités du contrôleur vers de repo

---

Tools/Services/InterneAuthentifierService.php

Hi,
This PR corrects a bug where `:` is not allowed in passwords.
(it replaces https://github.com/libertempo/web/pull/723)
Thank you 👍

Allow ':' in password

---

Tests/Units/Tools/Services/LdapAuthentifierService.php
Tools/Services/LdapAuthentifierService.php

À l'origine, l'utilisateur avait le choix ou non d'avoir une connexion sécurisée. #51 a enlevé ce choix alors je le remets, en découvrant automatiquement ce que l'utilisateur voulait.
Au passage, la méthode précédent de vérification des identifiants dans le serveur LDAP n'était pas adapté à tous, on trouve donc une méthode plus générale.

Choix du protocole pour ldap

---

Utilisateur/UtilisateurRepository.php

Un bug un peu vicelard. Le token a une durée de vie au moment où il est généré et cette durée est repoussée à chaque fois que l'API est interrogée. Normalement.
En réalité, ce qui se passait jusque là était que la durée de vie restait fixe suite à l'authentification. Je corrige ça.

Vrai comportement de session

---

Tests/Units/Tools/Services/LdapAuthentifierService.php
Tools/Services/LdapAuthentifierService.php

un patch express pour permettre l'authentification avec un active directory en plus d'openldap. Je ne l'ai pas testé pour le moment, je le ferai dés que possible.

Authentification openldap et AD

---

Tools/Services/AAuthentifierFactoryService.php

Si le caractère ":" est contenu dans le mot de passe, `explode()` l'interprétait comme un séparateur de champ. Ce patch limite simplement `explode()` à 2 champs.

explode uniquement le premier ":"

---

Heure/Repos/ReposEntite.php
Heure/Repos/ReposRepository.php
Makefile
Tests/Units/Heure/Repos/ReposEntite.php
Tests/Units/Heure/Repos/ReposRepository.php
Tools/App.php
Tools/Controllers/HeureReposEmployeController.php
Tools/Controllers/HeureReposUtilisateurController.php
Tools/Middlewares/AccessChecker.php
Tools/Middlewares/Identificator.php
Tools/Route/Absence.php
Tools/Route/Heure.php
decisions.md

Cf. #10 
Ajout des heures de repos de l'employé courant, tests unitaires compris. La route désormais dispo est  : 
* GET `/employe/me/heure/repos `
Après mûre réflexion, je ne vois pas de mauvaise pratique à ce que l'utilisateur courant soit embarqué dans la request, je l'y place donc pour qu'il soit consommé là où c'est nécessaire. Ici en tant que prédicat de filtre automatique de la récolte des heures, à terme dans d'autres routes `/me`.
Comme à mon habitude, j'en ai profité pour améliorer le makefile.

Heure de repos pour l'employé

---

Solde/SoldeEntite.php
Solde/SoldeRepository.php
Tests/Functionals/SoldeCest.php
Tests/Units/Solde/SoldeEntite.php
Tests/Units/Solde/SoldeRepository.php
Tools/App.php
Tools/Controllers/SoldeEmployeController.php
Tools/Middlewares/AccessChecker.php
Tools/Route/Heure.php
Tools/Route/Solde.php

Petite PR pour obtenir le solde de l'employé connecté. Route : `/employe/me/solde`
Le test consiste simplement à s'assurer que la requête retourne le solde de chaque type de congé de l'employé.

Solde de l'employé en cours

---

Tests/Units/Tools/Controllers/AbsenceTypeController.php
Tests/Units/Tools/Controllers/GroupeController.php
Tests/Units/Tools/Controllers/GroupeEmployeController.php
Tests/Units/Tools/Controllers/GroupeGrandResponsableController.php
Tests/Units/Tools/Controllers/GroupeResponsableController.php
Tests/Units/Tools/Controllers/JournalController.php
Tests/Units/Tools/Controllers/PlanningController.php
Tests/Units/Tools/Controllers/PlanningCreneauController.php
Tests/Units/Tools/Libraries/AController.php
Tests/Units/Tools/Libraries/ARestController.php
Tools/Controllers/AbsencePeriodeController.php
Tools/Controllers/AbsenceTypeController.php
Tools/Controllers/AuthentificationController.php
Tools/Controllers/GroupeController.php
Tools/Controllers/GroupeEmployeController.php
Tools/Controllers/GroupeGrandResponsableController.php
Tools/Controllers/GroupeResponsableController.php
Tools/Controllers/HeureAdditionnelleEmployeController.php
Tools/Controllers/HeureReposEmployeController.php
Tools/Controllers/JourFerieController.php
Tools/Controllers/JournalController.php
Tools/Controllers/PlanningController.php
Tools/Controllers/PlanningCreneauController.php
Tools/Controllers/SoldeEmployeController.php
Tools/Controllers/UtilisateurController.php
Tools/Libraries/AController.php
Tools/Middlewares/DBConnector.php
composer.json
composer.lock
di-config.php

Cf. #100 #115 
On continue à faire en douceur (Cc. K. Owen et son No-op, No-op, No-op, Interface :heart:).
Ici, il s'agit d'ajouter l'ORM à proprement parlé comme dépendance du système et d'injecter l'entityManager là où il va devoir être utilisé. Il n'a aucun impact pour le moment. Les prochaines PRs s'attacheront à muter le comportement du contrôleur pour outrepasser le repo.
La relecture est aisée ; puisque c'est souvent les mêmes lignes, les deltas se verront vite. Là encore, il n'est pas nécessaire de tester.

ORM : ajouter l'entityManager

---

di-config.php

#115 n'a pas été parfaitement conçue et j'ai oublié de mettre une dépendance dans le DIC. Cette erreur est désormais corrigée.

Ajout d'une dépendance manquante

---

.semver
Tools/Controllers/UtilisateurEmployeController.php
Tools/Middlewares/AccessChecker.php
Tools/Route/Utilisateur.php
Utilisateur/UtilisateurRepository.php

Pour obtenir les informations de l'utilisateur courant il faut désormais utiliser la route `/employe/me`.
Pour tester, il suffit de s'assurer que la requête `/employe/me` retourne bien les informations de l'utilisateur courant uniquement.

route employe/me

---

Absence/Type/Entite.php
Absence/Type/TypeEntite.php
Absence/Type/TypeRepository.php
Tests/Units/Absence/Type/TypeRepository.php
Tools/Controllers/AbsenceTypeController.php

La prochaine version de Libertempo permettra de désactiver les types d'absences... Ce PR permet de retourner la valeur du champ ta_actif par /absence/type.

"Types absences" désactivable
